### ISSUE TITLE
Tweaking Values not loading when configuring new PC tokens

### ISSUE THREAD

**Issue by GrandMasterElby** [melek/Simple5e#4]
When creating a new PC token and clicking "Configure Token" in the GM Token Management macro group, the Tweaking Values popup does not load. The following error is printed to chat instead. 

```
Invalid condition in IF(getSightType() == "Normal") roll option.       
Statement options (if any): if(getSightType() == "Normal")       
Statement Body : vSightTypeIndex = 0; vSightTypeIndex = if(getSightType() == "Darkvision", 1, 2)
```

Players are able to access this page through their respective sheet, and using "Configure Token" on an otherwise configured token does not reproduce the issue. 

Edit: formatting

**Comment by melek** [comment]
This has been fixed!

- [x] Updated in 2.1 Campaign File
- [x] Updated in Simple5e Wiki
- [x] Updated in 2.0 -> 2.1 Patch token

**Comment by melek** [comment]
Actually, this issue was incorrectly closed!

The bug appears to be specifically when players create the token themselves. There may be workarounds to this, but since the fix is trivial I think I will document the error and workarounds rather than complicate the framework to deal with the bug. I will also report it on the MapTool forums.

### Recommended Workaround
When creating tokens, players should double-click them to open the editor and hit 'Ok'. This will fix the sight value for the token so the Tweak Token dialog will work.

**Comment by melek** [comment]
https://github.com/RPTools/maptool/issues/1828
